# Generated by Django 5.1.2 on 2025-01-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="biography",
            field=models.CharField(
                blank=True, db_column="BIOGRAPHY", max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="profileimg",
            field=models.ImageField(
                blank=True,
                db_column="PROFILEIMG",
                max_length=300,
                null=True,
                upload_to="userimg/",
            ),
        ),
    ]
