# Generated by Django 5.1.3 on 2025-02-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_favoritedproducts_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRooms',
            fields=[
                ('chatroomid', models.AutoField(db_column='ChatRoomID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ChatRooms',
                'managed': False,
            },
        ),
    ]
