# Generated by Django 5.1.3 on 2025-02-19 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_chatrooms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'managed': True},
        ),
    ]
