# Generated by Django 5.1.3 on 2025-03-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_chatrooms_alter_users_profileimg'),
        ('main', '0008_products_color_products_size_products_tags_and_more'),
    ]

    operations = [
    ]
