# Generated by Django 5.1.3 on 2025-03-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_20250304_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notifid', models.AutoField(db_column='NOTIFID', primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='CONTENT', max_length=500, null=True)),
                ('link', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='LINK', max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Notifications',
                'managed': False,
            },
        ),
    ]
