# Generated by Django 5.1.2 on 2025-02-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_users_profileimg"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoritedProducts",
            fields=[
                (
                    "favoritedproductsid",
                    models.AutoField(
                        db_column="FavoritedProductsID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateTimeField(blank=True, db_column="Date", null=True)),
            ],
            options={
                "db_table": "FavoritedProducts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Followers",
            fields=[
                (
                    "followerid",
                    models.AutoField(
                        db_column="FollowerID", primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateTimeField(blank=True, db_column="Date", null=True)),
            ],
            options={
                "db_table": "Followers",
                "managed": False,
            },
        ),
    ]
